### ISSUE TITLE
Silent error on product type null or empty

### ISSUE THREAD

**Issue by LupusUmbrae** [senbox-org/snap-desktop#11]
I was trying to open a sentinal 3 'like' data product but the SNAP toolbox just appeared to attempt to open the file, but ended up doing nothing. After looking through the log file and then the github code i found that the issue was in the NetCDF file's global attributes `Conventions` was a blank string.

The issue however is that the GUI did not actually display any error message or any useful information about what the issue was. This line in the [Product] (https://github.com/senbox-org/snap-engine/blob/master/snap-core/src/main/java/org/esa/snap/core/datamodel/Product.java#L281) is raising the exception but nothing is seen on the GUI.

I was using version 2.0.2 (just switched to 3)

**Comment by TonioF** [comment]
These sort of errors should be reported by the UI. I have added a new check which should cause that an error message is given.
