### ISSUE TITLE
Pixel informations timestamp not changing on AATSR TOA L1B file

### ISSUE THREAD

**Issue by LupusUmbrae** [senbox-org/snap-desktop#14]
Hello,

I've been using SNAP to view an AATSR TOA L1B file (filename below) and noticed that when i inspect the pixel information the timestamp doesn't appear to change.

Opening the same file in BEAM however shows the timestamp (hours, minutes, seconds) changing as my pointer moves along the image.

AATSR TOA L1B filename: `ATS_TOA_1PUUPA20120408_034259_000065273113_00262_52862_6804.N1` - Hopefully you're able to find this file.

Thanks in advance,
Robin

**Comment by marpet** [comment]
Thanks for this report.
It was [a bug](https://senbox.atlassian.net/browse/SNAP-470) not only for AATSR. It is now fixed and will be published with the next release. Maybe there will also be a module update soon, but can't promise yet.

Thanks again
Marco
