### ISSUE TITLE
Mask manager with geometries Landsat 8

### ISSUE THREAD

**Issue by anaruescas** [senbox-org/snap-desktop#19]
I cannot see the ROIs I have drawn with the geometry tools in my Landsat 8 image as masks in the Mask Manager.

**Comment by marpet** [comment]
Hi Ana,

this is related to the multi-size character of Landsat 8. If you open it on a resampled size by using _Import/Optical Sensors/Landsat/Landsat8 in [15|30]m_ from the menu it should work. It should also work if you use the _Raster/Geometric Operations/Resampling_ operation.
I've created an [issue in our JIRA](https://senbox.atlassian.net/browse/SNAP-538) for this, so we keep track of it.

Thanks
