### ISSUE TITLE
SNAP Doesn't show all bands

### ISSUE THREAD

**Issue by LupusUmbrae** [senbox-org/snap-desktop#20]
I've been having a lot of issues with SNAP seemingly randomly choosing which bands to display from the NetCDF files.

Each file we use has a varaible format of `name` and `name_orphan`, what we are seeing is that SNAP only ever shows wither the `name` or the `name_orphan` variable in the bands. However this seems to be somewhat random as to which one it shows. However it is always either all orphan bands or all none-orphan bands.

Opening the same product on two different machines can also lead to a different result.

We are seeing this issue with real SLSTR NetCDF products as well as NetCDF files we are generating locally.

Screen shot of the bands and variable metadata
![snap band issue](https://cloud.githubusercontent.com/assets/914585/18200135/4eee1702-70fb-11e6-914f-4f0f3755e51b.PNG)

NcML definition for file
```
<?xml version="1.0" encoding="UTF-8"?>
<ncml:netcdf xmlns:ncml="http://www.unidata.ucar.edu/namespaces/netcdf/ncml-2.2" location="Z:/Nightly/2016-09-01_15-01/S3A_SL_1_RBT____20120408T034259_20120408T052812_20160901T114053_6313_113_262______TBC_R_NT____.SEN3/geodetic_in.nc">
  <ncml:dimension name="columns" length="512" />
  <ncml:dimension name="rows" length="42959" isUnlimited="true" />
  <ncml:dimension name="orphan_pixels" length="0" isUnlimited="true" />
  <ncml:attribute name="Conventions" value="NetCDF" />
  <ncml:attribute name="title" value="AT SLSTR-Like L1 Radiance and Brightness Temperatures Product. (Measurements + Annotations)" />
  <ncml:attribute name="institution" value="TVUK" />
  <ncml:attribute name="source" value="Test" />
  <ncml:attribute name="history" value="Test" />
  <ncml:attribute name="comment" value="Test" />
  <ncml:attribute name="references" value="Test" />
  <ncml:attribute name="contact" value="Test" />
  <ncml:attribute name="netCDF_version" value="4.4.0 of Jun  3 2016 15:16:32 $" />
  <ncml:attribute name="product_type" value="NetCDF" />
  <ncml:attribute name="product_name" value="unset" />
  <ncml:attribute name="creation_time" value="1472730053327" />
  <ncml:attribute name="validity_start_time" value="0000-00-00T00:00:00.000000" />
  <ncml:attribute name="validity_stop_time" value="0000-00-00T00:00:00.000000" />
  <ncml:attribute name="resolution" value="[1000 1000]" />
  <ncml:attribute name="start_offset" type="double" />
  <ncml:attribute name="track_offset" type="double" />
  <ncml:attribute name="absolute_orbit_number" type="long" value="0" />
  <ncml:variable name="elevation_in" shape="rows columns" type="short">
    <ncml:attribute name="standard_name" value="surface_altitude" />
    <ncml:attribute name="long_name" value="Surface elevation of detector FOV centre above reference ellipsoid" />
    <ncml:attribute name="units" value="m" />
    <ncml:attribute name="scale_factor" type="double" value="0.1" />
    <ncml:attribute name="add_offset" type="double" value="0.0" />
    <ncml:attribute name="valid_min" type="short" value="-450" />
    <ncml:attribute name="valid_max" type="short" value="9000" />
    <ncml:attribute name="_FillValue" type="short" value="-999" />
    <ncml:attribute name="_ChunkSizes" type="int" value="8 512" />
  </ncml:variable>
  <ncml:variable name="elevation_orphan_in" shape="rows orphan_pixels" type="short">
    <ncml:attribute name="standard_name" value="surface_altitude" />
    <ncml:attribute name="long_name" value="Surface elevation of detector FOV centre above reference ellipsoid" />
    <ncml:attribute name="units" value="m" />
    <ncml:attribute name="scale_factor" type="double" value="0.1" />
    <ncml:attribute name="add_offset" type="double" value="0.0" />
    <ncml:attribute name="valid_min" type="short" value="-450" />
    <ncml:attribute name="valid_max" type="short" value="9000" />
    <ncml:attribute name="_FillValue" type="short" value="-999" />
    <ncml:attribute name="_ChunkSizes" type="int" value="64 64" />
  </ncml:variable>
  <ncml:variable name="latitude_in" shape="rows columns" type="int">
    <ncml:attribute name="standard_name" value="latitude" />
    <ncml:attribute name="long_name" value="Latitude of detector FOV centre on the earth's surface" />
    <ncml:attribute name="units" value="degrees_north" />
    <ncml:attribute name="scale_factor" type="double" value="1.0E-6" />
    <ncml:attribute name="add_offset" type="double" value="0.0" />
    <ncml:attribute name="valid_min" type="int" value="-91" />
    <ncml:attribute name="valid_max" type="int" value="91" />
    <ncml:attribute name="_FillValue" type="int" value="-999" />
    <ncml:attribute name="_ChunkSizes" type="int" value="4 512" />
  </ncml:variable>
  <ncml:variable name="latitude_orphan_in" shape="rows orphan_pixels" type="int">
    <ncml:attribute name="standard_name" value="latitude" />
    <ncml:attribute name="long_name" value="Latitude of detector FOV centre on the earth's surface" />
    <ncml:attribute name="units" value="degrees_north" />
    <ncml:attribute name="scale_factor" type="float" value="1.0E-6" />
    <ncml:attribute name="add_offset" type="float" value="0.0" />
    <ncml:attribute name="valid_min" type="int" value="-91" />
    <ncml:attribute name="valid_max" type="int" value="91" />
    <ncml:attribute name="_FillValue" type="int" value="-999" />
    <ncml:attribute name="_ChunkSizes" type="int" value="45 45" />
  </ncml:variable>
  <ncml:variable name="longitude_in" shape="rows columns" type="int">
    <ncml:attribute name="standard_name" value="longitude" />
    <ncml:attribute name="long_name" value="Longitude of detector FOV centre on the earth's surface" />
    <ncml:attribute name="units" value="degrees_east" />
    <ncml:attribute name="scale_factor" type="double" value="1.0E-6" />
    <ncml:attribute name="add_offset" type="double" value="0.0" />
    <ncml:attribute name="valid_min" type="int" value="-181" />
    <ncml:attribute name="valid_max" type="int" value="181" />
    <ncml:attribute name="_FillValue" type="int" value="-999" />
    <ncml:attribute name="_ChunkSizes" type="int" value="4 512" />
  </ncml:variable>
  <ncml:variable name="longitude_orphan_in" shape="rows orphan_pixels" type="int">
    <ncml:attribute name="standard_name" value="longitude" />
    <ncml:attribute name="long_name" value="Longitude of detector FOV centre on the earth's surface" />
    <ncml:attribute name="units" value="degrees_east" />
    <ncml:attribute name="scale_factor" type="float" value="1.0E-6" />
    <ncml:attribute name="add_offset" type="float" value="0.0" />
    <ncml:attribute name="valid_min" type="int" value="-181" />
    <ncml:attribute name="valid_max" type="int" value="181" />
    <ncml:attribute name="_FillValue" type="int" value="-999" />
    <ncml:attribute name="_ChunkSizes" type="int" value="45 45" />
  </ncml:variable>
</ncml:netcdf>

```

**Comment by LupusUmbrae** [comment]
Looks like the issue is in your [VariableMap](https://github.com/senbox-org/snap-engine/blob/master/snap-netcdf/src/main/java/org/esa/snap/dataio/netcdf/util/VariableMap.java#L76)

you're trying to store variables by their name but there is no requirement for different NetCDF variables to have unique names. And if we consider the Sentinel 3 - [SLSTR Product Specification](https://sentinel.esa.int/documents/247904/1872792/Sentinel-3_Product_Data_Format_Specification-SLSTR_Level-1-2_Products) it's possible to see that the orphan and none orphan fields share the same standard name.

This means that opening a single SLSTR Product (i.e. NetCDF file) will cause only one set of the variables to show, either orphan or none orphan and this behaviour could be random (as we've seen locally).

**Comment by marpet** [comment]
Thanks for the input. We will have a look at it. But it might take till early October.

**Comment by LupusUmbrae** [comment]
The issue is in how the CfNetCdfReaderPlugin attempts to find the band group to use, when it reads our NetCDF file it has two DimKey's, one which contains out orphans and one which contains the non-orphan data.

The function [getBestRasterDim](https://github.com/senbox-org/snap-engine/blob/master/snap-netcdf/src/main/java/org/esa/snap/dataio/netcdf/util/RasterDigest.java#L105) attempts to select the group based on its dimensions ([isTypicalRasterDim](https://github.com/senbox-org/snap-engine/blob/master/snap-netcdf/src/main/java/org/esa/snap/dataio/netcdf/util/DimKey.java#L112), one of [lon, long, longitude, ni, NX, SX, x, xc, across_track, numRows] for x, or similair for y).

However in our case we have the three dimension defined rows, columns and orphan_pixels. so in this case neither our orphan or non-orphan meet this criteria.

If it wasn't typical the `getBestRasterDim` instead takes the one with the most dimensions in a first come first serve. So something the first DimKey is the orphan and sometimes its the non-orphan. Looking at the [hashcode](https://github.com/senbox-org/snap-engine/blob/master/snap-netcdf/src/main/java/org/esa/snap/dataio/netcdf/util/DimKey.java#L143) for DimKey it completely depends on the length of our variables, so it's possible that if we write say x orphans we would get the orphans view, but when we write less/more than x we'd get non-orphan.

I think the ideal solution at this point is user intervention over what to show, for instance we may want to view orphans or non-orphans but the CfNetCDFReader will only let us view one band group.

In the mean time a quick solution would be to add [row, rows] and [col, cols, column, columns] to the [Typical dim names](https://github.com/senbox-org/snap-engine/blob/master/snap-netcdf/src/main/java/org/esa/snap/dataio/netcdf/util/DimKey.java#L33).

I will test a locally modified DimKey (along with the team here) to see if this works.

Hope this investigation helps :)

**Comment by marpet** [comment]
I've taken your quick solution suggestion. In the longer term we want to rework the NetCDF reader so I don't want tot spent to much effort on this right now.

Thanks for your help.
