### ISSUE TITLE
Incorrectly displaying NetCDF Long values

### ISSUE THREAD

**Issue by LupusUmbrae** [senbox-org/snap-desktop#22]
Given the following variable definition:

``` xml
<variable name='y_in' type='long' shape='rows columns' >
  <attribute name='long_name' value='Geolocated y (along track) coordinate of detector FOV centre' />
  <attribute name='units' value='m' />
  <attribute name='scale_factor' value='0.01 ' type='double' />
  <attribute name='add_offset' value='0.0 ' type='double' />
  <attribute name='_ChunkSizes' value='2  512 ' type='int' />
</variable>
```

We can see that we have an NcML type of Long which translates to a Java long. The values i have in this variable range from 0->~4,196,348,726, however in snap the min/max are reported as:

```
Minimum:    -2.1474835650000002E7   m
Maximum:    2.1474836400000002E7    m
```

It looks like Snap is instead of handling longs by converting it to two Integer's and offering me two different bands; Least Significant Bytes and Most Significant Bytes (LSB & MSB). Neither of which give me the correct values.

Is SNAP currently able to handle Long's for NetCDF? if not could it please?

**Comment by marpet** [comment]
Currently SNAP can't handle data of type long well. Recently SNAP has been extended for long but it is not yet fully supported. But we can put it on the agenda.
https://senbox.atlassian.net/browse/SNAP-608
