### ISSUE TITLE
GUI Layout Issues

### ISSUE THREAD

**Issue by LupusUmbrae** [senbox-org/snap-desktop#23]
Hello,

I'm seeing some strange behaviour on the SNAP GUI.

The last few times i've opened snap my `Tool Windows` have been moving around, i had never moved the standard `Project Explorer`, `Pixel Info`, ect from the left hand side, however they randomly moved to be on the right hand side. Just now i opened it and they were displayed below the main view area (where my products are opened).

Also in the screen shot you can see that `Navigation` and `Colour manipulation` are referencing a product this is not open (but was last time i used SNAP).

I cannot see a reset tools window option like i can for toolbars. Is there an easy way to reset the GUI layout? or do i just need to delete some files from app data?

![snap_layout_issue](https://cloud.githubusercontent.com/assets/914585/19475548/a763870a-952c-11e6-8a5f-2b3c71a58cdb.PNG)

Let me know if you want a copy of any of my local files for investigation.

Thanks,
Robin

**Comment by marpet** [comment]
Hi Robin, I haven't heard about this behaviour nor experienced it myself. Really strange.
Maybe you can attach the message log files here.
What will reset the windows is the Action you find in the Window menu, named "Reset Windows". It should bring back the default configuration.

**Comment by LupusUmbrae** [comment]
Here's my messages.log file
[messages.txt](https://github.com/senbox-org/snap-desktop/files/536131/messages.txt)

**Comment by marpet** [comment]
Do you still experience this?

**Comment by marpet** [comment]
We are closing the issues in GitHub in favour of discussing them in the [SNAP Forum](https://forum.step.esa.int) and having the tickets in [JIRA](https://senbox.atlassian.net).
So please ask again in the forum if you have further questions.
