### ISSUE TITLE
Incorrect coordinates in export to geotiff

### ISSUE THREAD

**Issue by Sistjerne** [senbox-org/snap-desktop#26]
Hi,

I am trying to convert an Enisat ASAR image (.N1) to geotiff. In the GUI the coordinates are right, but when I export the image to geotiff (both through export and data conversion) the coordinates are wrong by many degrees.

Best regards

**Comment by lveci** [comment]
It's best to post this on the SNAP forum http://forum.step.esa.int/
Coordinates on a map projection should only be correct after geocoding with a DEM with terrain correction.

**Comment by Sistjerne** [comment]
Thanks I will do that the next time
