### ISSUE TITLE
How can I download org.netbeans.junit.jar？

### ISSUE THREAD

**Issue by kristenstewert11** [senbox-org/snap-desktop#27]
Hi sir :

I'm a chinese student , a rookie . I want to run your code https://github.com/senbox-org/snap-desktop/blob/master/snap-application/src/test/java/org/esa/snap/gui/SnapAppTest.java, but I can't find org.netbeans.junit.jar download link , can you help me? thank u very much.

**Comment by TonioF** [comment]
I suggest you follow the instructions from this link: https://senbox.atlassian.net/wiki/display/SNAP/How+to+build+SNAP+from+sources . If you do this, all required dependencies will be downloaded automatically.
Also, please note that we have a forum where you can ask questions: http://forum.step.esa.int
