### ISSUE TITLE
Loosing georeferencing parameter while exporting ALOS PALSAR/ALOS2 data to geotiff

### ISSUE THREAD

**Issue by aaqibjavad** [senbox-org/snap-desktop#28]
geotif looses all georeference parameters when ALOS data is exported

**Comment by marpet** [comment]
Do you mean it is not geo-coded anymore? And to which ALOS data are you referring to?
Alos2 Palsar or Alos Avnir2 or Prism?
In general I think it would be better to dicuss this in our [forum ](http://forum.step.esa.int/)

**Comment by marpet** [comment]
Ups, sorry. Only now I read the title carefully.
But still my first question is valid.

**Comment by aaqibjavad** [comment]
thanks for your response
I am facing this issue with Sentinel-1 Toolbox / SNAP
hen I open ALOS1 PALSAR data and try to export it into any other format, like ENVI format or GeoTIFF, the coordinates are not taken with the export. 

The ENVI format .hdr file does not contain any spatial reference in it as I open the exported ENVI file or GeoTIFF file in any other software, it shows me the data, but there are no coordinates.

for this i use Radar Mosaic and then export, after this it shows spatial parameters
Best Regards

**Comment by marpet** [comment]
@lveci Luis, do you know this? Is this a problem of Palsar?

**Comment by lveci** [comment]
I don't have a problem exporting ALOS PALSAR to GeoTiff with its coordinates on the master branch. At one point there was a problem with the lazy loading of ALOS tie point grids which could have caused this but, it should be fine in release 5.
