### ISSUE TITLE
Wrong coordinates for LandSat-8 RGB

### ISSUE THREAD

**Issue by DrSergius** [senbox-org/snap-desktop#31]
Excuse me for disturbance, maybe this issue has been already decribed and solved.

Steps:
1. Open LandSat-8 product (MTL TXT file)
2. Open RGB image window
3. Check the coordinates in "World View" window (they are correct)  [see screenshot 1](https://yadi.sk/i/d1WWV_pV33VmC8)
and then - in RGB window [see screenshot 2](https://yadi.sk/i/rlibyipw33VmP7)

Used SNAP 4 and SNAP 5 - situation is the same.

--
Regards, Sergey.

**Comment by marpet** [comment]
Hello Sergey,
thanks for the report. But this is not a bug. The coordinates are only displayed in a different format.
In the RGB view Degree° Minutes' Seconds'' is shown and in the WorldWind view decimal degrees are shown.
The conversion give these results:
45° 20' 57'' --> 45.34917
32° 29' 37'' --> 32.49361
I've used this http://www.satsig.net/degrees-minutes-seconds-calculator.htm to do the conversion.
So the shown coordinates are pretty close. You can also switch to decimal degrees for the RGB view.
Go to Tools/Options and the to General/Geo-Location. There yoou find the setting "Show geographical coordinates in decimal degrees"

cheers
  Marco

**Comment by DrSergius** [comment]
Excuse me, Marco and thanks a lot!

But there is one more question.
After export this RGB image as GeoTIFF and opening in QGIS - got the following situation:
[see screenshot](https://yadi.sk/i/kUzpj54733Vyhy)
But its OK for Sentinel-2 products - they are displayed correctly in my QGIS project.

--
Regards, Sergey.

**Comment by marpet** [comment]
Now you've found a bug.
Please see my [issue](https://senbox.atlassian.net/browse/SNAP-648) in our bug tracker. I've also written how you can workaround it.

Thanks a lot

**Comment by DrSergius** [comment]
Many thanks for "workaround path"!
Also hope that the bug will be fixed.

--
Regards, Sergey.
