### ISSUE TITLE
Cannot connect to update centre

### ISSUE THREAD

**Issue by riche** [senbox-org/snap-desktop#35]
I have updated to SNAP 5.0 and upon starting I was informed there where updated I needed to get.
I click to accept and install updates, it proceeds to downloading Plugins and fails.
The error screen that pops up is attached.
Any help appreciated.
Regards,

Richard.

![image](https://user-images.githubusercontent.com/2005195/26983204-e8f247f6-4d32-11e7-9a59-b0fbe76aeb8a.png)

**Comment by kraftek** [comment]
Hello.

The link to update center works fine, just tested that.
Maybe there was a temporary glitch of the internet connection.
You can retry to download the updates.
To see if the connection to the update center is ok, you can just type the url above in a browser address field and see if the download starts.

Regards
