### ISSUE TITLE
SNAP Error, linux version

### ISSUE THREAD

**Issue by tawnyowl** [senbox-org/snap-desktop#42]
Dears,
I'm using the latest SNAP 5.0 desktop version on a Linux desktop (Scientific Linux 7.4, Kernel: Linux 3.10.0-693.2.2.el7.x86_64), and get the following pop-up message error:
![snap_error](https://user-images.githubusercontent.com/6231774/31609501-c9af8686-b274-11e7-8597-470ca657715b.png)
each time I launch SNAP, or I try to display or refresh the "Product Library" panel. The products contained in the targeted directories are not displayed.

Is this related to my local environment settings (default US English) or a SNAP issue ?
Thanks,
Best regards,
JC

**Comment by marpet** [comment]
Also reported in the forum:
http://forum.step.esa.int/t/reporting-snap-desktop-gui-error-linux-version/7465
