### ISSUE TITLE
Error when importing the PolSARPro product into SNAP toolbox

### ISSUE THREAD

**Issue by Saporr** [senbox-org/snap-desktop#45]
Hello,
I have a problem when I was trying to import the PolSARPro product into SNAP. I always have the error message like that.
![capture](https://user-images.githubusercontent.com/34471932/33873839-dfae32f8-df5f-11e7-9e72-f558fc01699f.JPG)
First, I imported the Palsar-2 level 1.1 into PolSARPro toolbox to geocoding and polarization decomposition. And then I  imported the PolSARPro product into SNAP because I want to convert this product into .tiff file. I clicked the link of File/Import/SAR Format/PolSARPro. But it didn't work. My computer is window 10. I used PolSARPro 5.1.2 and SNAP Desktop new version.

Please help me to fix this problem.

**Comment by marpet** [comment]
Could you please post this in our [forum](forum.step.esa.int/)? I think there it is better placed. Please add it to the S1TBX category. You can login to our forum with your GitHub account.

Thanks

**Comment by Saporr** [comment]
Yes of course. Thank you.

2017-12-12 17:30 GMT+09:00 Marco Peters <notifications@github.com>:
