### ISSUE TITLE
Multi Language Support

### ISSUE THREAD

**Issue by xujuntwt95329** [senbox-org/snap-desktop#47]
Hi, I'm using the snap-desktop to develop some GUI applications, but I want a multi-language version.
Is there any approach to add multi language support for snap-desktop？

I tried to modify some strings in the source code and it works, but it's quite inefficiency...

**Comment by marpet** [comment]
No, there is no support multiple languages. It was never intended to support other languages as English. And as you have noticed it is now quite a lot of work to do it.

**Comment by xujuntwt95329** [comment]
Thank you very much!
 I guess I should start a new internationalization project.
