### ISSUE TITLE
Create Stack

### ISSUE THREAD

**Issue by sergiomelo37** [senbox-org/snap-desktop#55]
I'm having trouble with the "Create Stack" tool. I use Ubuntu 18.04 and SNAP 6.0. I am joining two IW-GRDH images and the error message is:
  [Nodeld: 2-CreateStack] org.jblas.NativeBlas.dgemm (CCIIID [DII [DIID [DII] V
========xx============
![captura de tela de 2018-05-26 18-32-00](https://user-images.githubusercontent.com/38961653/40580734-2e772ff4-6113-11e8-8b64-76d5d4d05624.png)

**Comment by marpet** [comment]
Could you please post this issue in the S1-Toolbox (https://github.com/senbox-org/s1tbx/).
This issue is related to this toolbox not to SNAP in general.
Also in the forum there are some discusssions related to it. Maybe it can help.
https://forum.step.esa.int/search?q=NativeBlas
