### ISSUE TITLE
Product installer error 

### ISSUE THREAD

**Issue by Charlottebishop** [senbox-org/snap-desktop#56]
I am trying to open a .xml in desktop windows SNAP and having some issues with a 'no product reader installed' error with respect to .xml files.  any ideas?

**Comment by marpet** [comment]
What kind of XML file are you trying to open? Which kind of product do you want to use?

**Comment by Charlottebishop** [comment]
Hi sorry for the delay I have been travelling.  I was trying to open a Sentinel-2 product

**Comment by marpet** [comment]
Have you installed the S2Toolbox? Are you using the correct xml file (MTD_MSIL1C.xml)?

**Comment by Charlottebishop** [comment]
Hi actually the problem is with Sentinel-3 not Sentinel-2 but the issue is as described above.  Both S2 and S3 toolkits are installed in SNAP

**Comment by marpet** [comment]
The only thing I can suggest is to reinstall SNAP and try to open the xfdumanifest.xml of the S3 product.
Usually, it works.

**Comment by Charlottebishop** [comment]
Appreciated Marpet I shall take a look and see if that solves it!

**Comment by marpet** [comment]
We are closing the issues in GitHub in favour of discussing them in the [SNAP Forum](https://forum.step.esa.int) and having the tickets in [JIRA](https://senbox.atlassian.net).
So please ask again in the forum if you have further questions.
