### ISSUE TITLE
Updating SNAP via command line keeps CPU busy with no visible progress

### ISSUE THREAD

**Issue by ikselven** [senbox-org/snap-desktop#57]
**System used:**
A clean installation of SNAP 6.0 on Debian Stretch (Debian 9.5).

**Steps to reproduce:**
Run the following command:
```
$ snap --nosplash --nogui --modules --update-all
```
**Expected Result:**
The command prints its update info, updates all SNAP modules and finishes updating in reasonable time.

**Actual Result:**
The command prints its update info (see [this gist for the output](https://gist.github.com/ikselven/bcd7abe673974f79061f2a586ea2f9d5)) and updates all SNAP modules. After the line `updates=0` has been printed, there is no visible progress anymore, but SNAP is now keeping more than 1 CPU core busy. I do not know when the command exits, because I have aborted it with Ctrl+C after 30 min of waiting.

----------------------------------
A similar behaviour can be observed when running:
```
$ snap --nosplash --nogui --modules --list --refresh
```
--------------------
Updating via GUI works fine but is not a viable option for scripting.

Edit: added info about aborting the update

**Comment by marpet** [comment]
Thanks for the report. 

We rely on the NetBeans platform for the update mechanism. Unfortunately, it has some issues on the command line.

I've added your report to our [JIRA issue tracker](https://senbox.atlassian.net/browse/SNAP-927) and added a note to the [wiki page](https://senbox.atlassian.net/wiki/spaces/SNAP/pages/30539785/Update+SNAP+from+the+command+line).

We have also an issue when installing a new module [SNAP-835](https://senbox.atlassian.net/browse/SNAP-835).

**Comment by ikselven** [comment]
Given one has `pkill` installed (should be available in macOS most Linux distros by default, not sure about other BSDs though) and uses the JRE that comes with SNAP, a very crude workaround is:

```shell
snap --nosplash --nogui --modules --update-all 2>&1 | while read -r line; do
    echo "$line"
    [ "$line" = "updates=0" ] && sleep 2 && pkill -TERM -f "snap/jre/bin/java"
done
```

This will terminate the Java process the SNAP update launched when the line "updates=0" is printed.

**Comment by marpet** [comment]
Since we haven't updated yet to NetBeans 9 I can't tell.
But I haven't heard anything about the status. Probably it is not fixed in NetBeans 9. Probably we have to take care of this issue. Maybe in the SNAP 7 release.
