### ISSUE TITLE
displaying flipped image

### ISSUE THREAD

**Issue by lamonss** [senbox-org/snap-desktop#59]
I have opened a Sentinel 1 image it is flipped horizontally. While it is ok with Sentinel 2 images.
![snap flip](https://user-images.githubusercontent.com/23170186/44192306-98ec2780-a14c-11e8-8600-06ddb5ab3ef9.JPG)
Mohanraj

**Comment by marpet** [comment]
That's intended. You have a scene from a descending orbit. Sentinel-2 is already reprojected and provided on the UTM grid. But Sentinel-1 is not.
See also the discussion in the forum.
https://forum.step.esa.int/t/how-can-sentinel-1-images-be-un-flipped/5210
There is also mentioned how you can correct this.
