### ISSUE TITLE
Display issues after Monitor sleep

### ISSUE THREAD

**Issue by maximlamare** [senbox-org/snap-desktop#60]
On Linux Debian (desktop computer), when SNAP desktop is open and the computer monitors are put to sleep (i.e. screen locked), the SNAP interface doesn't display correctly upon awakening. See the snapshot. This issue forces the user to restart SNAP each time the monitors go to sleep.

![capture du 2018-09-20 16-45-00](https://user-images.githubusercontent.com/32132761/45887642-8c4a9700-bdbc-11e8-9bd9-7f9864dc84e3.png)

**Comment by marpet** [comment]
Hi Maxim,

That's strange. I haven't heard about it before. Is the system running as a VM? Are the latest display driver installed? 
When this is happening is the processor busy too?

**Comment by marpet** [comment]
We are closing the issues in GitHub in favour of discussing them in the [SNAP Forum](https://forum.step.esa.int) and having the tickets in [JIRA](https://senbox.atlassian.net).
So please ask again in the forum if you have further questions.

This one can be found at: [SNAP-1044](https://senbox.atlassian.net/browse/SNAP-1044)
