### ISSUE TITLE
Problem with Ubuntu 16.04: /home/$USER/.snap has to be writable

### ISSUE THREAD

**Issue by elmerehbi** [senbox-org/snap-desktop#61]
This is my first time installing the software. I am using Ubuntu 16.04 which introduced snap for (containerized) applications.

I installed it under `/home/$USER/esa_snap`, however I get the following warning when I launch SNAP:

> Make sure /home/$USER/.snap/system is writable.

Clicking OK does not launch the program. 

Why am I getting this warning and how can I solve?

**Comment by marpet** [comment]
Probably you are facing the same issue as reported here:
https://forum.step.esa.int/t/request-for-help-to-install-snap-toolbox-on-ubuntu-laptop/11794

**Comment by marpet** [comment]
We are closing the issues in GitHub in favour of discussing them in the [SNAP Forum](https://forum.step.esa.int) and having the tickets in [JIRA](https://senbox.atlassian.net).
So please ask again in the forum if you have further questions.
