### ISSUE TITLE
Error Import Sen2 Data 

### ISSUE THREAD

**Issue by Larrxilein** [senbox-org/snap-desktop#67]
Hello,

![fehlerimp](https://user-images.githubusercontent.com/44141869/48909779-7023ae80-ee6e-11e8-928f-b3af614bb005.JPG)

this error occurs all the time, when i try to import Sentinel 2 Data Level 1C. I already reinstalled SNAP and tried out different Datasets from different Dataportals (Esa Copernicus Hub and earthexplorer.net)

Does anybody have an idea, whats wrong? 
I rezipped the folders with zip7 and didnt moved it in any other folders. 

Thank you already! 
Best regards, 

Larissa

**Comment by Larrxilein** [comment]
@obarrilero No this didn´t work either. 
I solved the problem by not unzipping the folder. I added the zipped folder per drag and drop and it worked! :)

**Comment by obarrilero** [comment]
It is strange. Could you please share with me one of the jp2 problematic files to check it? Another reason could be a corrupted openjpeg binaries. Are they available in the folder \.snap\auxdata\openjpeg\[snapVersion]\openjpeg-2.1.0-win64\bin? (opj_dump.exe, opj_compress.exe, opj_decompress.exe)

**Comment by Larrxilein** [comment]
https://upload.uni-jena.de/data/5bfbc7953993c1.21066121/S2A_MSIL1C_20180112T184731_N0206_R070_T11SKU_20180112T203339.zip

The Link is avaiable for three month. The unzipped files are too big for uploading. So i just unzipped these files and tried to import the MTD_... file oder one of the .jpgs. Its not working. Thank you!

Larissa

**Comment by Larrxilein** [comment]
Hi, thanks for helping me! The link to the file for just one jp2 image is following:

https://upload.uni-jena.de/data/5bfc3164ec0648.57697870/T11SKU_20180112T184731_B01.jp2

The opj_dump is not working neither. So i think it must be an error during unzipping the folder.

**Comment by obarrilero** [comment]
The jp2 file is working properly on my PC, perhaps the problem are that the openjpeg binaries are corrupted. Please could you remove your folder ./snap/auxdata/openjpeg ? When you restart SNAP it will be regenerated. Try also to delete the cache before restarting SNAP (.snap/var/cache/s2tbx)

**Comment by marpet** [comment]
We are closing the issues in GitHub in favour of discussing them in the [SNAP Forum](https://forum.step.esa.int) and having the tickets in [JIRA](https://senbox.atlassian.net).
So please ask again in the forum if you have further questions.
